server:
  port: DYNAMICPORT
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "DYNAMICPASSWORD"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      mixer: false
      http: false
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 3
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: false
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""

logging:
  file:
    max-history: 1
    max-size: 3MB
  path: /app/logs/

  level:
    root: INFO
    lavalink: INFO
